// <auto-generated />
using System;
using HardwareTemplateBuilder.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardwareTemplateBuilder.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410130210_AddJobScopedTemplates")]
    partial class AddJobScopedTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "TemplateStorageLocation",
                            Value = ""
                        });
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.BulkAddDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("BulkAddDrafts");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.DoorMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DoorMaterials", t =>
                        {
                            t.HasCheckConstraint("CK_DoorMaterial_Material", "\"Material\" IN ('Metal', 'Wood', 'Both')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Material = "Metal"
                        },
                        new
                        {
                            Id = 2,
                            Material = "Wood"
                        },
                        new
                        {
                            Id = 3,
                            Material = "Both"
                        });
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.HardwareItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("HardwareItems");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.HardwareItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardwareItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HardwareItemId");

                    b.HasIndex("IndividualTemplateId");

                    b.HasIndex("JobId");

                    b.ToTable("HardwareItemTemplates");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.IndividualTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoorMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnlineLink")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PagesToPrint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PagesToRotate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("DoorMaterialId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OriginJobId");

                    b.ToTable("IndividualTemplates");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MissingTemplateNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotesUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobAttachments");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobHardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalloutRemarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("HardwareItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HardwareItemId");

                    b.HasIndex("JobId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("JobHardware");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobReleases");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobTemplateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PagesToPrint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PagesToRotate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationDirection")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("SnapshotLocalLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndividualTemplateId");

                    b.HasIndex("JobId");

                    b.ToTable("JobTemplateSnapshots");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.ProjectManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectManagerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectManagers");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultTemplateSaveLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.BulkAddDraft", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Description", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Description", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.HardwareItem", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Description", "Description")
                        .WithMany("HardwareItems")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Manufacturer", "Manufacturer")
                        .WithMany("HardwareItems")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.HardwareItemTemplate", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.HardwareItem", "HardwareItem")
                        .WithMany("HardwareItemTemplates")
                        .HasForeignKey("HardwareItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.IndividualTemplate", "IndividualTemplate")
                        .WithMany("HardwareItemTemplates")
                        .HasForeignKey("IndividualTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HardwareItem");

                    b.Navigation("IndividualTemplate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.IndividualTemplate", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Description", "Description")
                        .WithMany("Templates")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.DoorMaterial", "DoorMaterial")
                        .WithMany("Templates")
                        .HasForeignKey("DoorMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Manufacturer", "Manufacturer")
                        .WithMany("Templates")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "OriginJob")
                        .WithMany()
                        .HasForeignKey("OriginJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Description");

                    b.Navigation("DoorMaterial");

                    b.Navigation("Manufacturer");

                    b.Navigation("OriginJob");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Job", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.ProjectManager", "ProjectManager")
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.UserProfile", "UserProfile")
                        .WithMany("Jobs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProjectManager");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobAttachment", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany("Attachments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobHardware", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.HardwareItem", "HardwareItem")
                        .WithMany("JobHardwareLinks")
                        .HasForeignKey("HardwareItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany("JobHardwareLinks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.JobRelease", "Release")
                        .WithMany("HardwareLinks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HardwareItem");

                    b.Navigation("Job");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobRelease", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany("Releases")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobTemplateSnapshot", b =>
                {
                    b.HasOne("HardwareTemplateBuilder.Core.Models.IndividualTemplate", "IndividualTemplate")
                        .WithMany("Snapshots")
                        .HasForeignKey("IndividualTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HardwareTemplateBuilder.Core.Models.Job", "Job")
                        .WithMany("Snapshots")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualTemplate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Customer", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Description", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("HardwareItems");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.DoorMaterial", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.HardwareItem", b =>
                {
                    b.Navigation("HardwareItemTemplates");

                    b.Navigation("JobHardwareLinks");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.IndividualTemplate", b =>
                {
                    b.Navigation("HardwareItemTemplates");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Job", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("JobHardwareLinks");

                    b.Navigation("Releases");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.JobRelease", b =>
                {
                    b.Navigation("HardwareLinks");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.Manufacturer", b =>
                {
                    b.Navigation("HardwareItems");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.ProjectManager", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("HardwareTemplateBuilder.Core.Models.UserProfile", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
